services:
  - name: qr-code-app
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
